apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openedx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/UsamaTanoli/openedx-aws.git
    targetRevision: main
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: openedx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
